Repository SU-SWS/adapt-auth-sdk, pull requests merged in 2022-04, with the labels that each got.

#9 NOJIRA | @mattanglin | edge handler safe dependencies
  package-lock.json
  package.json
  src/AdaptAuth.ts
  src/types.ts
Labels: task, size/s, patch

#11 Delete merge-to-stage.yml
  .github/release-drafter.yml
  .github/workflows/merge-to-stage.yml
  .github/workflows/release.yml
Labels: size/xs

#12 NOJIRA | @mattanglin | extract jwt methods for edge handlers
  src/AdaptAuth.ts
  src/index.ts
  src/jwt.ts
Labels: task, size/xs
